version: '3.9'


services:
  db-epoch:
    image: postgres:16
    container_name: postgres_db-epoch
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin000
      POSTGRES_DB: myepoch
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

